# Helpers for *.adoc.erb

def do_not_edit_generated_file
  (<<~ASCIIDOC).strip
    //////////////////////////////////////////////////////////////
    //                                                          //
    //             * DO  NOT  EDIT  THIS  FILE  ! *             //
    //                                                          //
    //  It is autogenerated, your changes will be overwritten.  //
    //                Modify *.adoc.erb instead.                //
    //                                                          //
    //////////////////////////////////////////////////////////////
  ASCIIDOC
end

def github_link(org, repo)
  %Q(https://github.com/#{org}/#{repo}[#{repo}])
end

def shield_code_climate(org, repo)
  shield_url = "https://codeclimate.com/github/#{org}/#{repo}/badges/gpa.svg"
  shield_link = "https://codeclimate.com/github/#{org}/#{repo}"
  shield_alt_text = "Code Climate"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_commits_since(org, repo)
  shield_url =
    "https://img.shields.io/github/commits-since/#{org}/#{repo}/latest.svg"
  shield_link = "https://github.com/#{org}/#{repo}/releases"
  shield_alt_text = "Commits since latest"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_gem(name)
  shield_url = "https://img.shields.io/gem/v/#{name}.svg"
  shield_link = "https://rubygems.org/gems/#{name}"
  shield_alt_text = "Gem Version"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_gha_rake(org, repo)
  shield_url = "https://github.com/#{org}/#{repo}/workflows/rake/badge.svg"
  shield_link = "https://github.com/#{org}/#{repo}/actions?workflow=rake"
  shield_alt_text = "Build Status (Rake)"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_gha_macos(org, repo)
  shield_url = "https://github.com/#{org}/#{repo}/workflows/macos/badge.svg"
  shield_link = "https://github.com/#{org}/#{repo}/actions?workflow=macos"
  shield_alt_text = "Build Status (macOS)"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_gha_ubuntu(org, repo)
  shield_url = "https://github.com/#{org}/#{repo}/workflows/ubuntu/badge.svg"
  shield_link = "https://github.com/#{org}/#{repo}/actions?workflow=ubuntu"
  shield_alt_text = "Build Status (Ubuntu)"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_gha_windows(org, repo)
  shield_url = "https://github.com/#{org}/#{repo}/workflows/windows/badge.svg"
  shield_link = "https://github.com/#{org}/#{repo}/actions?workflow=windows"
  shield_alt_text = "Build Status (Windows)"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_gha_generate(org, repo)
  shield_url = "https://github.com/#{org}/#{repo}/workflows/generate/badge.svg"
  shield_link = "https://github.com/#{org}/#{repo}/actions?workflow=generate"
  shield_alt_text = "Build Status"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_gha_docker(org, repo)
  shield_url = "https://github.com/#{org}/#{repo}/workflows/docker/badge.svg"
  shield_link = "https://github.com/#{org}/#{repo}/actions?workflow=docker"
  shield_alt_text = "Build Status (Docker)"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_gha_test(org, repo)
  shield_url = "https://github.com/#{org}/#{repo}/workflows/test/badge.svg"
  shield_link = "https://github.com/#{org}/#{repo}/actions?workflow=test"
  shield_alt_text = "Build Status"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield_gha(org, repo, workflow)
  url = "https://github.com/#{org}/#{repo}/workflows/#{workflow}/badge.svg"
  link = "https://github.com/#{org}/#{repo}/actions?workflow=#{workflow}"
  alt_text = "Build Status (#{workflow})"

  shield(url, alt: alt_text, link: link)
end

def shield_pull_requests(org, repo)
  shield_url = "https://img.shields.io/github/issues-pr-raw/#{org}/#{repo}.svg"
  shield_link = "https://github.com/#{org}/#{repo}/pulls"
  shield_alt_text = "Pull Requests"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

require 'net/http'
require 'json'

def shield_gha_latest_release(org, repo, workflow = "rake")
  release_url = "https://api.github.com/repos/#{org}/#{repo}/releases/latest"
  tag_name = JSON.parse(Net::HTTP.get(URI(release_url)))["tag_name"]

  shield_url = "https://github.com/#{org}/#{repo}/actions/workflows/#{workflow}.yml/badge.svg?branch=#{tag_name}"
  shield_link = "https://github.com/#{org}/#{repo}/actions/workflows/#{workflow}.yml?query=branch%3A#{tag_name}"
  shield_alt_text = "Latest release"

  shield(shield_url, alt: shield_alt_text, link: shield_link)
end

def shield(img, link:, alt:)
  %Q(image:#{img}["#{alt}",link="#{link}"])
end
