name: Build dashboard

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:

jobs:
  readme:
    name: Build README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Install dependencies
        run: gem install asciidoctor

      - name: Build release dashboard
        run: make all

      - name: Print README.adoc
        run: cat README.adoc

      - name: Commit release dashboard
        if: github.event_name != 'pull_request'
        id: commit
        run: |
          git config --local user.email "open.source@ribose.com"
          git config --local user.name "GitHub Action"
          mv README.adoc .github/README.adoc
          git add -f .github/README.adoc
          git commit -m "Update release dashboard"
          git push origin HEAD:${GITHUB_REF}
        continue-on-error: true
